routes/web.php
<?php

use App\Http\Controllers\CenterController;
use App\Http\Controllers\CityController;
use App\Models\Center;
use App\Models\City;
use App\Models\User;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Notification;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
| 
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
| 
*/
define('PAGINATION_COUNT',10);


Route::get('/', function () {
    return view('welcome');
});
Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');
Route::get('/dashboard', function () {
    return view('dashboardpanal.admin.welcome');
})->name('dashboard');
Route::middleware('auth')->group(function(){
    Route::resource('centers',CenterController::class);
    Route::resource('cities',CityController::class);
    Route::get('centers-archive',[CenterController::class,'archive'])->name('centers-archive');
    Route::get('trash/{id}',[CenterController::class,'trash'])->withTrashed()->name('trash');
    Route::get('restore/{center}',[CenterController::class,'restore'])->withTrashed()->name('restore');
    Route::post('/currency/ajax_search', [CenterController::class,'ajax_search'])->name('currency.ajax_search');
    Route::get('noti',function (){
        $user=Auth::user();
        foreach($user->unreadNotifications as $notification){
            $notification -> markAsRead();
        }
        // return $notifications;
        return view('notifications.index',compact('user'));
    })->name('noti');
    Route::get('read11/{id}',function($id){
        $notification = auth()->user()->notifications()->where('id', $id)->first();
            if ($notification) {
                $notification->markAsRead();
                return back();
            }
    })->name('read11');
    Route::get('test',function (){
        $center=Center::findOrFail(1);
        return $center->user->name;
    });
    Route::get('profile',function (){
        $user=User::findOrFail(Auth::user()->id);
        return view('profile',compact('user'));
    });
});
Auth::routes();

app/Models/Center.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class Center extends Model
{
    use HasFactory,SoftDeletes;
    protected $guarded=[];
    public function city(){
        return $this->belongsTo(City::class,'city_id');
    }
    public function parent(){
        return $this->belongsTo(Self::class,'center_id');
    }
    public function user(){
        return $this->belongsTo(User::class,'user_id');
    }
}

app/Http/Controllers/CenterController.php
<?php

namespace App\Http\Controllers;


use App\Http\Requests\CenterRequest;
use App\Models\Center;
use App\Models\City;
use App\Models\User;
use App\Notifications\deleteCenter;
use App\Notifications\NewEvent;
use App\Notifications\Restore;
use App\Notifications\UpdateCenter;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Notification;
use App\Helper\CustomHelper;
/**
 * Custom Helper Class
 *
 * @author Mohammad Sulaiman
 */

class CenterController extends Controller
{
    // field input 

    private $fields = ['name', 'notes', 'city_id', 'parent_id', 'user_id', 'address'];

    // this property for model object 

    private $model;

    // name of blade files 

    private $fileBlade = 'centers';

    public function construct()
    {

        $this->model = new Center(); // initialize the property 
    }
    /**
     * Display the index page with a list of Currency records.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\View\View
     */

    public static function message($route, $type, $content)
    {
        return redirect()->route($route)->with($type, $content);
    }
    public function index()
    {
        try {
            $centers = Center::paginate(10);
            return view('centers.index', compact('centers'));
        } catch (\Exception $e) {
            return self::message('centers.index', 'error', 'هنالك خطأ ما ');
        }
    }
    public function create()
    {
        try {
            $cities = City::get();
            $centers = Center::get();
            // Return the create view with the user's notificationsc
            return view($this->fileBlade . '.create', compact('cities', 'centers'));
        } catch (\Exception $e) {
            return self::message('centers.index', 'error', 'هنالك خطأ ما ');
        }
    }
    public function store(CenterRequest $request)
    {
        try {
            // Prepare data for creating a new Currency record

            $data = CustomHelper::prepareData($request, $this->fields);

            // $center = Center::create($request->all() + ['user_id' => Auth::user()->id]);
            $center=$this->model::create($data);
            if ($center->save()) {
                $users = User::all();
                Notification::send($users, new NewEvent($center));
                return self::message('centers.index', 'message', 'creating center successfuly');
            } else
                return back();
        } catch (\Exception $e) {
            return self::message('centers.index', 'error', 'هنالك خطأ ما ');
        }
    }
    public function show(Center $center)
    {
        return view('centers.show', compact('center'));
    }
    public function edit(Center $center)
    {
        try {
            $cities = City::all();
            $centers = Center::all();
            return view('centers.edit', compact('center', 'cities', 'centers'));
        } catch (\Exception $e) {
            return self::message('centers.index', 'error', 'هنالك خطأ ما ');
        }
    }
    public function update(Request $request, $id) // why it's not working with CenterRequest.
    {
        try {
            $item = Center::findOrFail($id);
            $old = $item->name;
            $newData = $request->all();
            if ($this->dataHasChanged($item, $newData)) {
                if ($item->update($request->all())) {
                    $users = User::all();
                    Notification::send($users, new UpdateCenter($item, $old));
                    return redirect()->route('centers.index')->with('message', 'تم تعديل المركز بنجاح');
                }
            } else return back()->with('error', 'حدث مشكلة ما');
        } catch (\Exception $e) {
            return self::message('centers.index', 'error', 'هنالك خطأ ما ');
        }
    }
    public function destroy(Center $center)
    {
        try {
            $center1 = $center;
            if ($center->delete()) {
                $users = User::all();
                $user = User::findOrFail(Auth::user()->id);
                Notification::send($users, new deleteCenter($center1, $user));
                return redirect()->route('centers.index')->with('message', 'تم حذف المركز بنجاح');
            } else
                return back();
        } catch (\Exception $e) {
            return self::message('centers.index', 'error', 'هنالك خطأ ما');
        }
    }
    public function archive()
    {
        try {
            $centers = Center::onlyTrashed()->paginate(10);
            return view('centers.archive', compact('centers'));
        } catch (\Exception $e) {
            return self::message('centers.index', 'error', 'هنالك خطأ ما ');
        }
    }
    public function trash($id)
    {
        try {
            $center = Center::onlyTrashed()->findOrFail($id);
            $center->forceDelete();
            return redirect()->route('centers.index')->with('message', 'تم حذف المركز بشكل نهائي');
        } catch (\Exception $e) {
            return self::message('centers.index', 'error', 'هنالك خطأ ما ');
        }
    }
    public function restore(Center $center)
    {
        try {
            if ($center->restore()) {
                $users = User::get();
                Notification::send($users, new Restore($center));
                return redirect()->route('centers.index');
            } else
                return back();
        } catch (\Exception $e) {
            return self::message('centers.index', 'error', 'هنالك خطأ ما');
        }
    }
    public function ajax_search(Request $request)
    {
        try {
            if ($request->ajax()) {
                $search_by_text = $request->search_by_text;
                if (!empty($search_by_text)) {
                    $centers = Center::where('name', 'LIKE', '%' . $search_by_text . '%')->get();
                    return view('centers.ajax_search', compact('centers'));
                } else {
                    $data = Center::select()->orderby('id', 'ASC');
                    return view('centers.ajax_search', compact('centers'));
                }
            }
        } catch (\Exception $ex) {
            return self::message('centers.index', 'error', 'هنالك خطأ ما ');
        }
    }
    // function for check if data are changed or not 
    // it's for update action
    private function dataHasChanged($item, $newData)
    {
        foreach ($newData as $key => $value) {
            if ($item->$key != $value) {
                return true;
            }
        }
        return false;
    }
}

resources/views/centers/ajax_search.blade.php
@foreach ($centers as $center)
<tr>
  <th scope="row">{{$center->id}}</th>
  <td>{{$center->name}}</td>
  <td>{{$center->city->name}}</td>
  <td>{{$center->address}}</td>
  @if ($center->center_id != null)
  <td>{{$center->parent->name}}</td>
  @else
  <td>-</td>
  @endif
  <td>{{$center->notes}}</td>
  <td>
    <a href="{{route('centers.show',$center)}}" class="btn btn-outline-info"><i class="fa-solid fa-eye"></i></a>
    <a href="{{route('centers.edit',$center)}}" class="btn btn-outline-warning"><i class="fa-solid fa-pen-to-square"></i></a>
    <form action="{{route('centers.destroy',$center)}}" class="d-inline-block" method="POST">
      @csrf
      @method('DELETE')
      <button class="btn btn-outline-danger" type="submit"><i class="fa-solid fa-trash"></i></button>
    </form>
  </td>
</tr>
@endforeach

resources/views/centers/archive.blade.php
@extends('dashboardpanal.layouts.admin')

@section('title')
@endsection

@section('breadcrumb')
    <a href="{{ route('dashboard') }}" class="nav-link">الضبط العام</a>
@endsection
@section('contentheader')

@endsection
@section('contentheaderlink')
سلة المحذوفات
@endsection
@section('contentheaderactive')
المؤسسات
@endsection
@section('content')
{{-- <h1 class="text-info d-block text-center mb-4">سلة المحذوفات</h1> --}}
  <table class="table">
    <thead style="background-color: #fab1a0">
      <tr>
        <th scope="col">#</th>
        <th scope="col">اسم المركز</th>
        <th scope="col">المدينة</th>
        <th scope="col">العنوان</th>
        <th scope="col">تابعة ل</th>
        <th scope="col">ملاحظات</th>
        <th scope="col">افعال</th>
      </tr>
    </thead>
    <tbody id="itemTableBody">
      <?php $i=0?>
      @foreach ($centers as $center)
      <tr>
        <th scope="row">{{++$i}}</th>
        <td>{{Str::limit($center->name,30)}}</td>
        <td>{{$center->city->name }}</td>
        <td>{{Str::limit($center->address,30)}}</td>
        @if ($center->center_id != null)
        @if (isset($center->parent->name))
        <td>{{Str::limit($center->parent->name,30)}}</td>
        @else
        <td>-</td>
        @endif
        @else
        <td>-</td>
        @endif
        <td>{{Str::limit($center->notes,20)}}</td>
          <td>
            <form action="{{route('restore',['center'=>$center])}}" class="d-inline-block" method="GET">
                @csrf
                <button class="btn btn-outline-info" type="submit"><i class="fa-solid fa-trash-can-arrow-up"></i></button>
              </form>
          <form action="{{route('trash',['id'=>$center->id])}}" class="d-inline-block" method="GET">
            @csrf
            <button class="btn btn-outline-danger" type="submit"><i class="fa-solid fa-trash"></i></button>
          </form>
        </td>
      </tr>
      @endforeach
    </tbody>
  </table>
  <div class="d-flex">
    {!! $centers-> links()!!}
  </div>
@endsection

resources/views/centers/create.blade.php
@extends('dashboardpanal.layouts.admin')

@section('title')
@endsection

@section('breadcrumb')
    <a href="{{ route('dashboard') }}" class="nav-link">الضبط العام</a>
@endsection

@section('contentheader')
@endsection

@section('contentheaderlink')
@endsection

@section('contentheaderactive')

@endsection

@section('content')
<form action="{{route('centers.index')}}" method="POST">
  @csrf
  <div class="row mb-4">
  </div>
  <div class="form-outline mb-4">
    <input type="text" id="form6Example3" class="form-control" name="name" required maxlength="80"/>
    <label class="form-label text-primary" for="form6Example3" >اسم المؤسسة</label>
  </div>
  @error('name')
  <div class="text-danger">{{$message}}</div>
  @enderror
  <!-- Text input -->
  <div class="form-outline mb-4">
    <input type="text" id="form6Example4" class="form-control" name="address" required maxlength="200"/>
    <label class="form-label text-primary" for="form6Example4">العنوان</label>
  </div>
  <!-- Message input -->
  <div class="form-outline mb-4">
    <textarea class="form-control" id="form6Example7" rows="4"></textarea>
    <label class="form-label" for="form6Example7">ملاحظات</label>
  </div>
  <div class="col-md-3 mb-3">
 
    <label for="validationDefault04"> اختر مدينة</label>
    <select class="custom-select" id="validationDefault04" required name="city_id">
      <option disabled selected>المدن</option>
      @foreach ($cities as $city)
      <option value="{{$city->id}}">{{$city->name}}</option>
      @endforeach
    </select>
  </div>
  @error('city_id')
  <div class="text-danger">{{$message}}</div>
  @enderror
  <div class="col-md-3 mb-3">
    <label for="validationDefault04">تابعة ل</label>
    <select class="custom-select" id="validationDefault04" required name="center_id">
      <option disabled selected>مؤسسة</option>
      @foreach ($centers as $center)
      <option value="{{$center->id}}">{{$center->name}}</option>
      @endforeach
    </select>
  </div>
  <input type="hidden" name="user_id" value="{{Auth::user()->id}}">
  <br>
  <div class="d-block w-100 text-center mt-5">
  <button type="submit" class="btn  btn-inline-block mb-4 w-25 mr-auto ml-auto text-center" style="background-color: #81ecec">إنشاء <i class="fa-solid fa-plus"></i></button>
  <a class="btn  btn-inline-block mb-4 w-25 mr-auto ml-auto" href="{{route('centers.index')}}" style="background-color: #fab1a0">إلغاء <i class="fa-solid fa-xmark"></i></a>
</div>
</form>
@endsection

resources/views/centers/edit.blade.php
@extends('dashboardpanal.layouts.admin')

@section('title')
@endsection

@section('breadcrumb')
    <a href="{{ route('dashboard') }}" class="nav-link"> تعديل</a>
@endsection

@section('contentheader')
@endsection

@section('contentheaderlink')
تعديل المؤسسة
@endsection

@section('contentheaderactive')
المؤسسات
@endsection

@section('content')
    <form action="{{ route('centers.update', $center) }}" method="POST">
        @csrf
        @method('PUT')
        <!-- 2 column grid layout with text inputs for the first and last names -->
        <div class="row mb-4">
        </div>
        <!-- Text input -->
        <div class="form-outline mb-4">
            <input type="text" id="form6Example3" class="form-control" name="name" value="{{ $center->name }}"/>
            <label class="form-label text-primary" for="form6Example3">اسم المؤسسة</label>
        </div>
        <!-- Text input -->
        <div class="form-outline mb-4">
            <input type="text" id="form6Example4" class="form-control" name="address" value="{{ $center->address }}" />
            <label class="form-label text-primary" for="form6Example4">العنوان</label>
        </div>
        <!-- Message input -->
        <div class="form-outline mb-4">
            <textarea class="form-control" id="form6Example7" rows="4" name="notes">{{ $center->notes }}</textarea>
            <label class="form-label" for="form6Example7">ملاحظات</label>
        </div>
        {{-- <select class="form-select form-select-lg mb-3" aria-label=".form-select-lg example">
            @foreach ($cities as $city)
                <option value="{{$city->id}}" {{ $city->id == $center->city_id ? 'selected' : '' }}>
                    {{$city->name}}
                </option>
            @endforeach
        </select> --}}
        <div class="col-md-3 mb-3">
 
            <label for="validationDefault04"> اختر مدينة</label>
            <select class="custom-select" id="validationDefault04" required name="city_id">
                @foreach ($cities as $city)
                <option value="{{$city->id}}" {{ $city->id == $center->city_id ? 'selected' : '' }}>
                    {{$city->name}}
                </option>
            @endforeach
            </select>
          </div>
          @error('city_id')
          <div class="text-danger">{{$message}}</div>
          @enderror
        {{-- <select class="form-select form-select-lg mb-3" aria-label=".form-select-lg example" name="center_id">
            @foreach ($centers as $center)
                @if ($center->id != $center->id)
                    <option value="{{ $center->id }}">{{ $center->name }}</option>
                @else
                @endif
            @endforeach
        </select> --}}
        <div class="col-md-3 mb-3">
            <label for="validationDefault04">تابعة ل</label>
            <select class="custom-select" id="validationDefault04" name="center_id">
                @foreach ($centers as $center)
                @if ($center->id != $center->id)
                    <option value="{{ $center->id }}">{{ $center->name }}</option>
                @else
                @endif
            @endforeach
            </select>
          </div>
        <!-- Submit button -->
        {{-- <div class="d-block w-100 text-center mt-5">
            <button type="submit" class="btn btn-primary btn-inline-block mb-4 w-25">تعديل <i class="fa-solid fa-pen-to-square"></i></button>
            <a class="btn btn-danger btn-inline-block mb-4 w-25 mr-auto ml-auto" href="{{ route('centers.index') }}">إلغاء
                <i class="fa-solid fa-xmark"></i></a>
        </div> --}}
        <br>
        <div class="d-block w-100 text-center mt-5">
        <button type="submit" class="btn  btn-inline-block mb-4 w-25 mr-auto ml-auto text-center" style="background-color: #81ecec">تعديل <i class="fa-regular fa-pen-to-square"></i></button>
        <a class="btn  btn-inline-block mb-4 w-25 mr-auto ml-auto" href="{{route('centers.index')}}" style="background-color: #fab1a0">إلغاء <i class="fa-solid fa-xmark"></i></a>
      </div>
    </form>
@endsection

resources/views/centers/index.blade.php
@extends('dashboardpanal.layouts.admin')

@section('title')
@endsection

@section('breadcrumb')
<a href="{{ route('centers.index') }}" class="nav-link">المؤسسات</a>
@endsection

@section('contentheader')

@endsection
@section('contentheaderlink')
عرض جميع المؤسسات
@endsection

@section('contentheaderactive')
المؤسسات
@endsection
@section('content')
<input type="hidden" id="token_search" value="{{csrf_token()}}">
<input type="hidden" id="ajax_search_url" value="{{ route('currency.ajax_search') }}">
<a href="{{route('centers.create')}}" class="btn btn-outline-success ml-auto mr-auto d-block mb-3 w-25">انشاء مؤسسة جديدة</a>
<div class="input-group rounded w-50 mr-auto ml-auto mb-3">
  <input type="search" class="form-control rounded" placeholder="بحث" id="search_by_text" aria-label="Search" aria-describedby="search-addon" />
  </span>
</div>
  <table class="table">
    <thead style="background-color:#81ecec ">
      <tr>
        <th scope="col">#</th>
        <th scope="col">اسم المركز</th>
        <th scope="col">المدينة</th>
        <th scope="col">العنوان</th>
        <th scope="col">تابعة ل</th>
        <th scope="col">ملاحظات</th>
        <th scope="col">افعال</th>
      </tr>
    </thead>
    <tbody id="itemTableBody">
      <?php $i=0?>
      @foreach ($centers as $center)
      <tr>
        <th scope="row">{{++$i}}</th>
        <td>{{Str::limit($center->name,30)}}</td>
        <td>{{$center->city->name }}</td>
        <td>{{Str::limit($center->address,30)}}</td>
        @if ($center->center_id != null)
        @if (isset($center->parent->name))
        <td>{{Str::limit($center->parent->name,30)}}</td>
        @else
        <td>-</td>
        @endif
        @else
        <td>-</td>
        @endif
        <td>{{Str::limit($center->notes,20)}}</td>
        <td>
          <a href="{{route('centers.show',$center)}}" class="btn btn-outline-info"><i class="fa-solid fa-eye"></i></a>
          <a href="{{route('centers.edit',$center)}}" class="btn btn-outline-warning"><i class="fa-solid fa-pen-to-square"></i></a>
          <form action="{{route('centers.destroy',$center)}}" class="d-inline-block" method="POST">
            @csrf
            @method('DELETE')
            <button type="button" class="btn btn-outline-danger" data-toggle="modal" data-target="#exampleModal"> <i class="fa-solid fa-trash"></i></button>
            <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog modal-confirm">
                  <div class="modal-content">
                      <div class="modal-header">
                          <div class="icon-box">
                              <i class="bi bi-x-lg" style="font-size: 2rem; color: #f15e5e;"></i>
                          </div>
                      </div>
                      <h4 class="modal-title">تأكيد عملية الحذف؟</h4>
                      <div class="modal-body">
                        <p>هل تريد حذف المؤسسة المحددة بشكل نهائي.</p>
                       </div>
                      <div class="modal-footer" style="margin-left:40px;">
                          <button type="submit" class="btn btn-danger">حذف</button>
                          <a type="button" class="btn btn-secondary" data-dismiss="modal">الغاء</a>
                      </div>
                  </div>
              </div>
          </div>
          </form>
        </td>
      </tr>
      @endforeach
    </tbody>
  </table>
  <div class="d-flex">
    {!! $centers->links() !!}
  </div>
@endsection

resources/views/centers/show.blade.php
@extends('dashboardpanal.layouts.admin')

@section('title')
@endsection

@section('breadcrumb')
    <a href="{{ route('dashboard') }}" class="nav-link">الضبط العام</a>
@endsection

@section('contentheader')
@endsection

@section('contentheaderlink')
عرض
@endsection
@section('contentheaderactive')
المؤسسات
@endsection

@section('content')
<div class="row">
  <div class="col-4">
    <div class="list-group" id="list-tab" role="tablist">
      <a class="list-group-item list-group-item-action active" id="list-home-list" data-toggle="list" href="#list-home" role="tab" aria-controls="home">اسم المؤسسة</a>
      <a class="list-group-item list-group-item-action" id="list-profile-list" data-toggle="list" href="#list-profile" role="tab" aria-controls="profile">العنوان</a>
      <a class="list-group-item list-group-item-action" id="list-messages-list" data-toggle="list" href="#list-messages" role="tab" aria-controls="messages">المدينة</a>
      <a class="list-group-item list-group-item-action" id="list-settings-list" data-toggle="list" href="#list-settings" role="tab" aria-controls="settings">تابعة ل </a>
    </div>
  </div>
  <div class="col-8">
    <div class="tab-content" id="nav-tabContent">
      <h1 class="tab-pane fade show active" id="list-home" role="tabpanel" aria-labelledby="list-home-list">{{$center->name}}</h1>
      <h1 class="tab-pane fade" id="list-profile" role="tabpanel" aria-labelledby="list-profile-list">{{$center->address}}</h1>
      <h1 class="tab-pane fade" id="list-messages" role="tabpanel" aria-labelledby="list-messages-list">{{$center->city->name}}</h1>
      <h1 class="tab-pane fade" id="list-settings" role="tabpanel" aria-labelledby="list-settings-list">
        @if (isset($center->parent->name))
        {{$center->parent->name}}
        @else
        مركز رئيسي
        @endif
      </h1>
    </div>
  </div>
</div>
@endsection